### PR TITLE
Added todo list copied code

### PR DESCRIPTION
**Pull request by BenjaminMatembe**
On this feature I added the  "To Do list"  project big chunk of code for my coding partner to review the best practices in the code.

### CODE REVIEW

**Comment by alvaroiporre** [comment]
Hi @BenjaminMatembe, Well done on the implementation of the functionality on this project, for the project:

✅ Runs well on the machine
✅ Has followed correct git flow

> # Required Changes ♻️

However, there are some **HTML and Javascript** best practices that you did not follow well and they need to be fixed for you to proceed to the next project but you are almost there 👍

1. Kindly, check your Stylelint linter because it is failing. You can use the `--fix` flag to fix it.

2. Read the comments below in your code and also implement the requested changes there and your code will be good to go 💯 .

Thank you and happy coding!!! 👍

**Comment by alvaroiporre** [comment]
https://github.com/BenjaminMatembe/bestPractices/blob/88a41e7d82be8b6c4487774da2f375c145e8ec9d/src/index.js#L26-L30
Kindly you could consider using a class Task to make your code more readable instead of an object.

**Comment by alvaroiporre** [comment]
https://github.com/BenjaminMatembe/bestPractices/blob/88a41e7d82be8b6c4487774da2f375c145e8ec9d/src/index.js#L56
Kindly consider re-using the `saveDataInLocalStorage()` function following the DRY Principle, instead of saving your data directly like the line above.

https://github.com/BenjaminMatembe/bestPractices/blob/88a41e7d82be8b6c4487774da2f375c145e8ec9d/src/modules/storage.js#L3-L5

**Comment by alvaroiporre** [comment]
https://github.com/BenjaminMatembe/bestPractices/blob/88a41e7d82be8b6c4487774da2f375c145e8ec9d/src/index.html#L13-L24
Kindly use HTML5 semantic tags over nested **section** tags, because here you will be following [html best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) and also It makes web pages more informative and adaptable, allowing browsers and search engines to better interpret content. Refer to this [guide](https://www.w3schools.com/html/html5_semantic_elements.asp) on how to use semantic tags, and also you could consider using the [header](https://www.w3schools.com/tags/tag_header.asp) tag instead of a **section** tag.

**Comment by alvaroiporre** [comment]
> 

jh

**Comment by BenjaminMatembe** [comment]
Hi @alvaroiporre thank you for reviewing my code and for the advising feedback given.
About using the **class** instead of an **object** I think the object is fine in this case and it does not affect the code readability.

About considering re-using the `saveDataInLocalStorage() `, I think for the case in which I used it , it is fine because am not calling the entire function but am just using one line of code to update the local storage with new object.

Thank you once again and you can kindly advise again incase!

**Comment by alvaroiporre** [comment]
Hi @BenjaminMatembe , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenjaminMatembe** [comment]
Hi @alvaroiporre thank you for giving me a go head by approving my pull request.

**Pull request merged**
